name: "JFrog Integration Example"
on:
  workflow_dispatch:

jobs:
  build:
     runs-on: ubuntu-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: Trim and Save Branch Name
         run: |
          BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///')
          echo $BRANCH_NAME
          SECRET_NAME="${BRANCH_NAME}_APP_KEY"
          echo "SC_NAME=$SECRET_NAME" >> $GITHUB_ENV
          
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           TEST_SC: ${{ secrets.$SC_NAME }}
           JF_URL: ${{ secrets.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
